stores:
  yaml:
    indent: 2
keys:
  - &user_theutz age1vlk29wfkfqff0c9yky2kwhp4c6zdwuzc7xd5xc8ydsldc9ulf99spwq9x2
  - &mach_konya age1fwmdgwcslxzvhzhd37ztcujl9elkccjezyq5p5mgxhq7ue8vqv0qujc6r4
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
      - age:
        - *user_theutz
        - *mach_konya
