session_name: slashfiles
start_directory: ./
global_options:
  remain-on-exit: true
  other-pane-width: 80
windows:
  - window_name: main
    layout: main-vertical
    panes:
      - shell_command: nvim
        sleep_before: 1
        focus: true
      - shell: nix develop -c watch

  - window_name: home-manager
    panes:
      - shell: man 5 home-configuration.nix

  - window_name: nix-darwin
    panes:
      - shell: man 5 configuration.nix

  - window_name: nvf
    panes:
      - shell: man 5 nvf

  - window_name: repl
    panes:
      - shell: nix repl nixpkgs
