session_name: slashfiles
start_directory: ./
global_options:
  remain-on-exit: true
  other-pane-width: 80
windows:
  - window_name: main
    layout: main-vertical
    panes:
      - shell_command: nvim
        sleep_before: 1
        focus: true
      - blank

  - window_name: man:nix
    panes:
      - shell: man 5 configuration.nix

  - window_name: man:home-manager
    panes:
      - shell: man 5 home-configuration.nix

  - window_name: man:nvf
    panes:
      - shell: man 5 nvf

  - window_name: nix-repl
    panes:
      - shell: nix repl nixpkgs
