session_name: slashfiles
start_directory: ./
global_options:
  remain-on-exit: true
windows:
  - window_name: main
    layout: main-vertical
    options:
      remain-on-exit: false
      other-pane-width: 100
    panes:
      - shell_command: nvim
        sleep_before: 1
        options:
          remain-on-exit: true
        focus: true
      - blank

  - window_name: home-manager
    panes:
      - shell: man 5 home-configuration.nix

  - window_name: nix-darwin
    panes:
      - shell: man 5 configuration.nix

  - window_name: nvf
    panes:
      - shell: man 5 nvf
